# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "인증서/프로비저닝 프로파일을 API Key로 재발급 (capability 변경 시)"

  lane :sync_certs do

    api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    match(
    	git_url: "git@github.com:khyeji98/RunningDiary-certificates.git",
    	storage_mode: "git",
    	type: "development",
    	api_key: api_key,
    	force: true
    )

    match(
    	git_url: "git@github.com:khyeji98/RunningDiary-certificates.git",
    	storage_mode: "git",
    	type: "appstore",
    	api_key: api_key,
    	force: true
    )
  end

  desc "Push a new beta build to TestFlight"

  private_lane :inject_private_configs do
    token = ENV["SECRETS_REPO_TOKEN"]
    sh("git clone https://#{token}@github.com/KimBaebae/rundiary-secrets.git .private --depth 1 --quiet")
    sh("cp .private/Secrets.xcconfig ../Config/Secrets.xcconfig")
    sh("rm -rf .private")
  end

  lane :beta do

    inject_private_configs

    # 0️⃣ 기존 Keychain 제거
    sh("security delete-keychain #{ENV['KEYCHAIN_NAME']} || true")

    # 1️⃣ Keychain 생성
    create_keychain(
    	name: ENV["KEYCHAIN_NAME"],
    	password: ENV["KEYCHAIN_PASSWORD"],
    	timeout: 3600,
    	default_keychain: true,
    	unlock: true,
    	lock_when_sleeps: false,
	add_to_search_list: true
    )

    # 2️⃣ Match 인증서/프로비저닝 설정
    match(
    	git_url: "git@github.com:khyeji98/RunningDiary-certificates.git",
    	storage_mode: "git",
    	type: "appstore",
    	readonly: true,
    	keychain_name: ENV["KEYCHAIN_NAME"],
    	keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    current_version = get_version_number

    latest_build_number=latest_testflight_build_number(
	api_key: api_key,
	version: current_version,
	initial_build_number: 0
    )

    increment_build_number(
	build_number: latest_build_number + 1
    )

    build_app(
      	project: "RunDiary.xcodeproj",
        scheme: "RunDiary-Release",
	export_method: "app-store",
	destination: "generic/platform=iOS",
	clean: true
    )

    upload_to_testflight(
	api_key: api_key,
	skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy a new version to the App Store"

  lane :release do

    inject_private_configs

    # 0️⃣ 기존 Keychain 제거
    sh("security delete-keychain #{ENV['KEYCHAIN_NAME']} || true")

    # 1️⃣ Keychain 생성
    create_keychain(
    	name: ENV["KEYCHAIN_NAME"],
    	password: ENV["KEYCHAIN_PASSWORD"],
    	timeout: 3600,
    	default_keychain: true,
    	unlock: true,
    	lock_when_sleeps: false,
	add_to_search_list: true
    )

    # 2️⃣ Match 인증서/프로비저닝 설정
    match(
    	git_url: "git@github.com:khyeji98/RunningDiary-certificates.git",
    	storage_mode: "git",
    	type: "appstore",
    	readonly: true,
    	keychain_name: ENV["KEYCHAIN_NAME"],
    	keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    current_version = get_version_number

    latest_build_number = latest_testflight_build_number(
	api_key: api_key,
	version: current_version,
	initial_build_number: 0
    )

    increment_build_number(
	build_number: latest_build_number + 1
    )

    build_app(
      	project: "RunDiary.xcodeproj",
        scheme: "RunDiary-Release",
	export_method: "app-store",
	destination: "generic/platform=iOS",
	clean: true
    )

    upload_to_app_store(
	api_key: api_key,
	force: true,
	skip_metadata: false,
	skip_screenshots: true,
	submit_for_review: true,
	automatic_release: true,
	run_precheck_before_submit: true,
	precheck_include_in_app_purchases: false
    )
  end
end
