# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"

  lane :beta do
    # 1️⃣ Keychain 생성
    create_keychain(
    	name: ENV["KEYCHAIN_NAME"],
    	password: ENV["KEYCHAIN_PASSWORD"],
    	timeout: 3600,
    	default_keychain: true,
    	unlock: true,
    	lock_when_sleeps: false,
	add_to_search_list: true
    )

    # 2️⃣ Match 인증서/프로비저닝 설정
    match(
    	git_url: "git@github.com:khyeji98/RunningDiary-certificates.git",
    	storage_mode: "git",
    	type: "appstore",
    	readonly: true,
    	keychain_name: ENV["KEYCHAIN_NAME"],
    	keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    sh("security unlock-keychain -p #{ENV['KEYCHAIN_PASSWORD']} ~/Library/Keychains/#{ENV['KEYCHAIN_NAME']}-db")
    sh("security set-keychain-settings -lut 21600 ~/Library/Keychains/#{ENV['KEYCHAIN_NAME']}-db")
    sh("security find-identity -p codesigning -v")

    api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    current_version = get_version_number

    latest_build_number=latest_testflight_build_number(
	api_key: api_key,
	version: current_version,
	initial_build_number: 0
    )

    increment_build_number(
	build_number: latest_build_number + 1
    )

    unlock_keychain(
      path: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASSWORD"],
      set_default: false
    )

    build_app(
      	project: "RunDiary.xcodeproj",
        scheme: "RunDiary",
	export_method: "app-store",
	destination: "generic/platform=iOS",
	clean: true
    )

    upload_to_testflight(
	api_key: api_key,
	skip_waiting_for_build_processing: true
    )
  end
end
