# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    create_keychain(
    	name: ENV["KEYCHAIN_NAME"],
    	password: ENV["KEYCHAIN_PASSWORD"],
    	timeout: 3600,
    	default_keychain: true,
    	unlock: true,
    	add_to_search_list: true
    )

    api_key = app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    match(
    	git_url: "git@github.com:khyeji98/RunningDiary-certificates.git",
    	storage_mode: "git",
    	type: "appstore",
    	readonly: true,
    	keychain_name: ENV["KEYCHAIN_NAME"],
    	keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    latest_build_number=latest_testflight_build_number(
	api_key: api_key
    )

    increment_build_number(
	build_number: latest_build_number + 1
    )

    build_app(
	scheme: "RunDiary",
	export_method: "app-store", # match type과 일치해야 함 (ad-hoc, development 등)
	export_options: {
	    provisioningProfiles: { 
		"com.kimhyeji.RunDiary" => "match AppStore com.kimhyeji.RunDiary"
    	    }
  	}
    )

    upload_to_testflight(
	api_key: api_key
    )
  end
end
