name: Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'RunDiary/**'
      - 'Dependencies/**'
      - 'RunDiary.xcodeproj/**'
      - 'RunDiary.xcworkspace/**'
      - 'Gemfile'
      - 'Gemfile.lock'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'RunDiary/**'
      - 'Dependencies/**'
      - 'RunDiary.xcodeproj/**'
      - 'RunDiary.xcworkspace/**'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 40

    env:
      SCHEME: RunDiary
      DESTINATION: "platform=iOS Simulator,name=iPhone 16"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -workspace RunDiary.xcodeproj/project.xcworkspace -scheme "$SCHEME"

      - name: Start xcode build 🛠
        run: |
          xcodebuild clean test -workspace RunDiary.xcodeproj/project.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage YES -skipMacroValidation -skipPackagePluginValidation
