name: Release

on:
  push:
    branches:
      - main

jobs:
  upload-appstore:
    name: Deploy to App Store
    runs-on: macos-latest

    steps:
      # 1️⃣ 체크아웃
      - name: 1️⃣ Checkout
        uses: actions/checkout@v4

      # 2️⃣ Xcode Version 설정
      - name: 2️⃣ Setting Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 🧹 Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Resolve Dependencies
        run: xcodebuild -resolvePackageDependencies -project RunDiary.xcodeproj

      - name: Skip Macro Validation
        run: |
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES

      - name: Verify Xcode & Swift
        run: |
          xcodebuild -version
          swift --version

      # 3️⃣ ruby 설치
      - name: 3️⃣ Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      # 4️⃣ 의존성 설치
      - name: 4️⃣ Install Dependencies
        run: bundle install

      # 5️⃣ Install SSH Key
      - name: 5️⃣ Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # 6️⃣ Run Fastlane
      - name: 6️⃣ Run Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: bundle exec fastlane release

      # 7️⃣ Get App Version
      - name: 7️⃣ Get App Version
        id: get_version
        run: |
          VERSION=$(agvtool what-marketing-version -terse1)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # 8️⃣ Create GitHub Release
      - name: 8️⃣ Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body_path: fastlane/metadata/ko/release_notes.txt
          draft: false
          prerelease: false
          # generate_release_notes: true # 릴리즈 노트 자동 생성(다음에 PR 올리면 활성화)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
